services:
  docs:
    image: speech_to_text_local_docs
    container_name: speech_to_text_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./speech_to_text:/app/speech_to_text:z
    ports:
      - '9000:9000'
    command: /start-docs
